version: "3.9"

services:
  app:
    image: node:22.18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    env_file:
      - .env
    ports:
      - "${NUXT_PORT:-3000}:3000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=forum
      - POSTGRES_PASSWORD=forum
      - POSTGRES_DB=forum
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
