version: "3.9"

services:
  app:
    image: node:22.18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    environment:
      # Nuxt dev server
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      # Current project uses SQLite by default
      - DATABASE_FILE=/app/forum.sqlite
      # Optional: Postgres connection string for future use
      - DATABASE_URL=postgres://forum:forum@db:5432/forum
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=forum
      - POSTGRES_PASSWORD=forum
      - POSTGRES_DB=forum
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
